services:
  # front:
  #   build: ./frontend/
  #   ports:
  #     - "80:3000"

  back:
    build: ./back
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - area
    command: /bin/sh -c "go run github.com/steebchen/prisma-client-go db push && ./back"


  db:
    image: postgres:13
    environment:
      POSTGRES_USER: dev
      POSTGRES_DB: area
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    networks:
      - area

networks:
  area:
    driver: bridge

