services:
  front:
    build: ./front/poc_front/
    ports:
      - "8081:3000"
    environment:
      - API_URL=http://back:8080
    networks:
      - area

  back:
    build: ./back
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - area

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: dev
      POSTGRES_DB: area
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    networks:
      - area

networks:
  area:
    driver: bridge

